######################################################################
# Automatically generated by qmake (2.01a) Wed Feb 13 06:16:19 2013
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += MyEditor.h
SOURCES += main.cpp MyEditor.cpp
RESOURCES += myeditor.qrc
